In [136]:
import json
import numpy as np


with open('Problem2.json') as json_file:  
    raw_data = json.load(json_file)
raw_data

{'Suppliers': [130, 55, 80, 65, 135],
 'Consumers': [130, 75, 65, 60, 75, 60],
 'Costs': [[6, 6, 8, 5, 4, 3],
  [2, 4, 3, 9, 8, 5],
  [3, 5, 7, 9, 6, 11],
  [3, 5, 4, 4, 2, 1],
  [2, 5, 6, 3, 2, 8]]}

In [137]:
suppliers = np.array(raw_data['Suppliers'])
consumers = np.array(raw_data['Consumers'])
costs = np.array(raw_data['Costs'])
capacity = np.zeros(costs.shape)

In [138]:
def satisfy(consumer_idx, cp_cons, cp_supp):
    supplier_index = 0
    while supplier_index < len(cp_supp):
        consumer = cp_cons[consumer_idx]
        supplier = cp_supp[supplier_index]
        if consumer==0: 
            break
        if supplier==0:
            supplier_index += 1
            continue
        capacity[supplier_index][consumer_idx] = consumer if supplier > consumer else supplier
        cp_cons[consumer_idx] -= capacity[supplier_index][consumer_idx]
        cp_supp[supplier_index] -= capacity[supplier_index][consumer_idx]
        supplier_index += 1

In [139]:
consumer_index = 0
while (consumer_index < len(consumers)) and (np.count_nonzero(capacity)!= len(consumers) + len(suppliers) - 1):
    cp_cons = np.copy(consumers)
    cp_supp = np.copy(suppliers)
    satisfy(consumer_index, cp_cons, cp_supp)
    idx = 0
    while idx < len(cp_cons):
        if idx != consumer_index: satisfy(idx, cp_cons, cp_supp)
        idx += 1
    if np.count_nonzero(capacity) == len(cp_cons) + len(cp_supp) - 1: break
    print("building new plan. old plan:")
    print(capacity)
    capacity = np.zeros(costs.shape)
    consumer_index += 1


building new plan. old plan:
[[130.   0.   0.   0.   0.   0.]
 [  0.  55.   0.   0.   0.   0.]
 [  0.  20.  60.   0.   0.   0.]
 [  0.   0.   5.  60.   0.   0.]
 [  0.   0.   0.   0.  75.  60.]]
building new plan. old plan:
[[55. 75.  0.  0.  0.  0.]
 [55.  0.  0.  0.  0.  0.]
 [20.  0. 60.  0.  0.  0.]
 [ 0.  0.  5. 60.  0.  0.]
 [ 0.  0.  0.  0. 75. 60.]]
building new plan. old plan:
[[65.  0. 65.  0.  0.  0.]
 [55.  0.  0.  0.  0.  0.]
 [10. 70.  0.  0.  0.  0.]
 [ 0.  5.  0. 60.  0.  0.]
 [ 0.  0.  0.  0. 75. 60.]]
building new plan. old plan:
[[70.  0.  0. 60.  0.  0.]
 [55.  0.  0.  0.  0.  0.]
 [ 5. 75.  0.  0.  0.  0.]
 [ 0.  0. 65.  0.  0.  0.]
 [ 0.  0.  0.  0. 75. 60.]]


In [135]:
capacity

array([[55.,  0.,  0.,  0., 75.,  0.],
       [55.,  0.,  0.,  0.,  0.,  0.],
       [20., 60.,  0.,  0.,  0.,  0.],
       [ 0., 15., 50.,  0.,  0.,  0.],
       [ 0.,  0., 15., 60.,  0., 60.]])