# Лабораторная работа №4

## Разработка программного средства на основе алгоритма задачи группового выбора вариантов.

### Основные теоретические положения

Групповой выбор сочетает в себе субъективные и объективные аспекты. Предпочтения каждого конкретного ЛПР субъективно и зависит от присущей данному человеку системы ценностей. В то же время объединение нескольких индивидуальных предпочтений в одно коллективное предпочтение должно осуществляться по возможности более объективным способом с помощью явно определенных формальных процедур.

Проблема коллективного выбора заключается в том как агрегировать индивидуальные предпочтения в интегральные оценки качества решения, на основе которых ищется наиболее предпочтительное решение.

### Метод предпочтений
Пусть имеется $m$ экспертов: $Э_{1}, Э_{2}, ..., Э_{m}$ и $n$ целей: $Z_{1}, Z_{2}, ..., Z_{n}$.

Каждый эксперт проводит оценку целей, пользуясь числами натурального ряда. Наиболее важной цели присваивается 1, менее важно -2 и т.д. В этих условиях веса целей определяются следующим образом:

1. Составляется исходная матрица предпочтений:

$Э_{j}/Z_{i}$ | $Z_{1}$ | $Z_{2}$ | ... | $Z_{n}$  
-- | ------ | -------- | --- | -------
$Э_{1}$ | $k_{11}$ | $k_{12}$ | ... | $k_{1n}$
$Э_{2}$ | $k_{21}$ | $k_{22}$ | ... | $k_{2n}$
...  | ... | ... | ... | ... 
$Э_{m}$ | $k_{m1}$ | $k_{m2}$ | ... | $k_{mn}$

$ 1 \leqslant k_{ji} \leqslant n, (j = 1,m, i = 1,n) $

2. Составляется модифицированная матрица предпочтений. С оценками
    
    $K_{ji} = n - k_{ji} (1<j<m; 1<i<n)$

3. Находятся суммарные оценки предпочтений по каждой цели:

    $k_{ji} = \sum_{}^{} k_{ji} (i = 1,n)$

4. Вычисляются исходные веса целей

    $w_{i}K_{i}/\sum_{}^{} K_{i} (i = 1,n)$, где $\sum_{}^{} w_{i} = 1$
    
#### Задание
Собрана группа экспертов в составе 3-х человек для выбора объекта инвестирования. Были предложены варианты:

- Минский автомобильный завод
- Минский завод холодильников «Атлант»
- Кондитерская фабрика «Витьба»
- ОАО «Нафтан»
- «Белкоммунмаш»
- Минская швейная фабрика «элема»

Оценки экспертов прибыльности предприятий приведены в матрице:

$Э_{j}/Z_{i}$ | $Z_{1}$ | $Z_{2}$ | $Z_{3}$ | $Z_{4}$ | $Z_{5}$ | $Z_{6}$
------------- | ------- | ------- | ------- | ------- | ------- | -------
$Э_{1}$ | 1 | 5 | 4 | 2 | 6 | 3
$Э_{2}$ | 3 | 4 | 1 | 6 | 5 | 2
$Э_{3}$ | 5 | 2 | 4 | 6 | 3 | 1

Где $Э_{1} ... i$ — эксперты, $Z_{1} ... j$ — проекты

Определить наиболее перспективный объект инвестирования.

##### Решение задачи

*Входные данные:*

In [61]:
import json
import numpy as np

with open("data/preference.json") as json_file:
        raw_data = json.load(json_file)

value = np.array(raw_data['value'], dtype=int)
    
print(f'Оценки экспертов:\n {value}')

Оценки экспертов:
 [[1 5 4 2 6 3]
 [3 4 1 6 5 2]
 [5 2 4 6 3 1]]


*Исходный код решения:*

In [62]:
# модифицированная матрица
mod = len(value[0]) - value

# суммарные оценки по целям
sumMod = mod.sum(axis=0)

# сумма всех оценок
sumV = sumMod.sum()

# веса целей
w = np.array([])
for el in sumMod:
    w = np.append(w, (el/sumV))

# вывод вариантов в порядке убывания по оптимальности
result = ""
w_c = w.copy()
for el in w:
    indMax = w_c.argmax()
    result = result + f'Z{indMax+1} > '
    w_c[indMax] = 0

*Результат выполнения:*

In [63]:
print(f'Модифицированная матрица:\n{mod}')
print(f'Суммарные оценки по целям: {sumMod}')
print(f'Веса целей: {w}')
print(f'Оптимальные варианты в порядке убывания: {result}')

Модифицированная матрица:
[[5 1 2 4 0 3]
 [3 2 5 0 1 4]
 [1 4 2 0 3 5]]
Суммарные оценки по целям: [ 9  7  9  4  4 12]
Веса целей: [0.2        0.15555556 0.2        0.08888889 0.08888889 0.26666667]
Оптимальные варианты в порядке убывания: Z6 > Z1 > Z3 > Z2 > Z4 > Z5 > 


### Метод рангов
Пусть имеется $m$ экспертов: $Э_{1}, Э_{2}, ..., Э_{m}$ и $n$ целей: $Z_{1}, Z_{2}, ..., Z_{n}$.

Каждый эксперт проводит оценку целей, пользуясь 10-бальной шкалой, причем оценки могут быть как целыми, так и дробными. В этих условиях веса целей определяются следующим образом:

1. Составляется матрица оценок экспертов:

$Э_{j}/Z_{i}$ | $Z_{1}$ | $Z_{2}$ | ... | $Z_{n}$  
-- | ------ | -------- | --- | -------
$Э_{1}$ | $S_{11}$ | $S_{12}$ | ... | $S_{1n}$
$Э_{2}$ | $S_{21}$ | $S_{22}$ | ... | $S_{2n}$
...  | ... | ... | ... | ... 
$Э_{m}$ | $S_{m1}$ | $S_{m2}$ | ... | $S_{mn}$

$ 0 \leqslant p_{ji} \leqslant 10, (j = 1,m, i = 1,n) $

2. Составляется матрица нормированных оценок:

$w = p_{ji}/\sum_{}^{} p_{ji} (j = 1,m, i = 1,n)$

3. Вычисляются искомые веса целей:

$w_{i} = \sum_{}^{} w_{ij}/\sum_{}^{}\sum_{}^{} w_{ij} (i = 1,n) \sum_{}^{} w_{i} = 1$
    
#### Задание
Анализ результатов экономической деятельности предприятия показал его неспособность функционировать на рынке. Пригласили 4-х экспертов для помощи руководству принять решение о выходе из сложившейся ситуации. Рассматриваются следующие варианты:

- Ликвидировать предприятие
- Выставить на продажу
- Объявить банкротом
- Провести санацию

Оценки экспертов прибыльности предприятий приведены в матрице:

$Э_{j}/Z_{i}$ | $Z_{1}$ | $Z_{2}$ | $Z_{3}$ | $Z_{4}$
------------- | ------- | ------- | ------- | -------
$Э_{1}$ | 2 | 3 | 4 | 1
$Э_{2}$ | 3 | 1 | 2 | 4
$Э_{3}$ | 1 | 4 | 3 | 2
$Э_{4}$ | 1 | 3 | 4 | 2

Где $Э_{1} ... i$ — эксперты, $Z_{1} ... j$ — проекты

Выяснить оптимальный путь дальнейшего развития предприятия.

##### Решение задачи

*Входные данные:*

In [133]:
with open("data/rank.json") as json_file:
        raw_data = json.load(json_file)

value = np.array(raw_data['value'], dtype=float)
    
print(f'Оценки экспертов:\n {value}')

Оценки экспертов:
 [[2. 3. 4. 1.]
 [3. 1. 2. 4.]
 [1. 4. 3. 2.]
 [1. 3. 4. 2.]]


*Исходный код решения:*

In [141]:
# модифицированная матрица
i=0
j=0
norm = np.copy(value)
for row in value:
    s = row.sum()
    for el in row:
        norm[i,j]=value[i,j]/s
        j = j + 1
    j=0
    i=i+1

# веса целей
w = norm.sum(axis=0)
w = w/norm.shape[0]

# вывод вариантов в порядке убывания по оптимальности
result = ""
w_c = w.copy()
for el in w:
    indMax = w_c.argmax()
    result = result + f'Z{indMax+1} > '
    w_c[indMax] = 0

*Результат выполнения:*

In [144]:
print(f'Матрица нормированных оценок:\n{norm}')
print(f'Веса целей: {w}')
print(f'Оптимальные варианты в порядке убывания: {result}')

Матрица нормированных оценок:
[[0.2 0.3 0.4 0.1]
 [0.3 0.1 0.2 0.4]
 [0.1 0.4 0.3 0.2]
 [0.1 0.3 0.4 0.2]]
Веса целей: [0.175 0.275 0.325 0.225]
Оптимальные варианты в порядке убывания: Z3 > Z2 > Z4 > Z1 > 


Полезные ссылки: http://victor-safronov.ru/systems-analysis/lectures/zhivickaya/29.html