# Лабораторная работа №3

## Разработка программного средства на основе алгоритмов многокритериального выбора вариантов.

### Классические критерии принятия решений

Критерий принятия решений - это функция, выражающая предпочтения лица, принимающего решения (ЛПР), и определяющая правило, по которому выбирается приемлемый или оптимальный вариант решения.

Всякое решение в условиях неполной информации принимается с учетом количественных характеристик ситуации, в которой принимаются решения. Наиболее часто применяются следующие критерии. Критерий Сэвиджа, критерий Гурвица, критерий Ходжа-Лемона, критерий Гермейера, минимаксный критерий, критерий Байеса-Лапласа и т. п.

Эти критерии можно использовать поочередно, причем после вычисления их значений среди нескольких вариантов приходится произвольным образом выделять некоторое окончательное решение. Что позволяет, во-первых, лучше проникнуть во все внутренние связи проблемы принятия решений и, во-вторых, ослабить влияние субъективного фактора.

Данные, необходимые для принятия решения в условии неопределенности, обычно задаются в форме матрицы, строки которой соответствуют возможным действиям, а столбцы – возможным состояниям системы.

Пусть, например, из некоторого материала требуется изготовить изделие, долговечность которого при допустимых затратах невозможно определить. Нагрузки считаются известными. Требуется решить, какие размеры должно иметь изделие из данного материала.

Варианты решения таковы:
- $E_{1}$ – выбор размеров из соображений максимальной долговечности;
- $E_{m}$ – выбор размеров из соображений минимальной долговечности;
- $E_{i}$ – промежуточные решения.

Условия требующие рассмотрения таковы:
- $F_{1}$ – условия, обеспечивающие максимальной долговечность;
- $F_{n}$ –условия, обеспечивающие min долговечность;
- $F_{i}$  –промежуточные условия.

Под результатом решения $e_{ij}=e(E_{i};F_{j})$ здесь можно понимать оценку, соответствующую варианту $E_{i}$ и условиям $F_{j}$ и характеризующие прибыль, полезность или надёжность. Обычно мы будем называть такой результат полезностью решения.

Тогда семейство (матрица) решений имеет вид:

 - | $F_{1}$ | $F_{2}$ | ... | $F_{n}$  
-- | ------ | -------- | --- | -------
$E_{1}$  | $e_{11}$ | $e_{12}$ | ... | $e_{1n}$
$E_{2}$  | $e_{21}$ | $e_{22}$ | ... | $e_{2n}$
...  | ... | ... | ... | ... 
$E_{m}$  | $e_{m1}$ | $e_{m2}$ | ... | $e_{mn}$

Чтобы прийти к однозначному и по возможности наилучшему варианту решения необходимо ввести оценочную (целевую) функцию. При этом матрица решений сводится к одному столбцу. Каждому варианту $E_{i}$ приписывается, некоторый результат $e_{ir}$, характеризующий, в целом, все последствия этого решения. Такой результат мы будем в дальнейшем обозначать тем же символом $e_{ir}$.

### Задание
Изучение экологической обстановки в районе города предполагает проведение исследований на наличие некоторых вредных веществ. Некоторые методики допускают частичное исследование на содержание вредных веществ. Таким образом, можно проводить полное исследование среды - $E_{1}$ или проводить исследование среды по сокращенной методике - $E_{2}$ или не проводить проверку вообще - $E_{3}$. При этом ситуация с загрязнением окружающей среды может быть: $F_{1}$ – загрязнение характеризуется сильным отклонением от нормы, $F_{2}$ – загрязнение имеет среднее отклонение от нормы, $F_{3}$ – отклонение незначительное. По результатам проверки принимаются меры уменьшающие загрязнения среды. Как следствие сокращаются затраты на оплату больничных листов. Таким образом в оценку результатов решений включают сокращение затраты на оплату больничных листов и затраты на проведение исследований (в т.р):

Варианты / Критерии выбора | $F_{1}$ | $F_{2}$ | $F_{3}$  
-------------------------- | ------- | ------- | -------
$E_{1}$  | -50,0 | -21,0 | -23,0
$E_{2}$  | -33,0 | -11,0 | 15,0
$E_{3}$  | 0,0 | 5,0 | 10,0

Подходящее решение следует выбрать, используя заданные критерии:
1. Критерий Байеса-Лапласа ($q_{1}=0,3$,$q_{2}=0,5$, $q_{3}=0,2$);
2. Критерий Ходжа-Лемана ($q_{1}=0,2$, $q_{2}=0,2$, $q_{3}=0,6$, $v=1/2$).

#### Критерий Байеса-Лапласа

Этот критерий учитывает каждое из возможных следствий. Пусть $q_{j}$ - вероятность появления внешнего состояния $F_{j}$, тогда для этого критерия оценочная функция запишется так:

$Z_{BL} = \max e_{ir}, e_{ir} = \sum_{}^{} e_{ij}q_{j}$.

Тогда правило выбора будет записано так: матрица решений дополняется еще одним столбцом, содержащим математическое ожидание значений каждой из строк. Выбираются те варианты $E_{io}$, в строках которых стоит наибольшее значение $e_{ir}$ этого столбца.

##### Решение задачи

*Входные данные:*

In [50]:
import json
import numpy as np

with open("data/bayes-laplace.json") as json_file:
        raw_data = json.load(json_file)

q = np.array(raw_data['q'], dtype=float)
e = np.array(raw_data['e'], dtype=float)
    
print(f'Мат. ожидания q: {q}')
print(f'Количественная оценка e:\n{e}')

Мат. ожидания q: [0.3 0.5 0.2]
Количественная оценка e:
[[-50. -21. -23.]
 [-33. -11.  15.]
 [  0.   5.  10.]]


*Исходный код решения:*

In [51]:
multE = e * q

# суммируем строки
sumE = multE.sum(axis = 1)

maxE = max(sumE)

# нахождение индекса максимального значения
result = sumE.argmax() + 1

*Результат выполнения:*

In [52]:
print(f'Получившаяся сумма строк: {sumE}')
print(f'Максимальное значение: {maxE}')
print(f'Выбран вариант №{result}')

Получившаяся сумма строк: [-30.1 -12.4   4.5]
Максимальное значение: 4.5
Выбран вариант №3


#### Критерий Ходжа-Лемана

Этот критерий опирается одновременно на ММ-критерий и критерий Байеса-Лапласа.

$Z_{HL}=\max e_{ir}$.

С помощью параметра $v$ выражается степень доверия к используемому распределению вероятностей. Если доверие велико, то доминирует критерий Баеса-Лапласа, в противном случае – ММ-критерий, т.е. мы ищем

$e_{ir}=v\sum_{j=1}^{n} e_{ij}q_{j}+(1-v)\underset{j}{\min} e_{ij}, 0 \leqslant v \leqslant 1$

Правило выбора, соответствующее критерию Ходжа-Лемана формируется следующим образом. Матрица решений дополняется столбцом, составленным из средних взвешенных значений (с весом $v=const$) математического ожидания и наименьшего результата каждой строки. Отбираются те варианты решений, в строках которого стоит набольшее значение этого столбца.

При $v = 1$ критерий Ходжа-Лемана переходит в критерий Байеса-Лапласа, а при $v = 0$ становится минимаксным.

Выбор $v$ субъективен. Для применения критерия Ходжа-Лемана желательно, чтобы ситуация в которой принимается решение, удовлетворяла свойствам:
- вероятности появления состояния $F_{j}$ неизвестны, но некоторые предположения о распределении вероятностей возможны;
- принятое решение теоретически допускает бесконечно много реализаций;
- при малых числах реализации допускается некоторый риск.

##### Решение задачи

*Входные данные:*

In [58]:
with open("data/hodges–lehmann.json") as json_file:
        raw_data = json.load(json_file)

q = np.array(raw_data['q'], dtype=float)
v = np.array(raw_data['v'], dtype=float)
e = np.array(raw_data['e'], dtype=float)
    
print(f'Мат. ожидания q: {q}')
print(f'Степень доверия v: {v}')
print(f'Количественная оценка e:\n{e}')

Мат. ожидания q: [0.2 0.2 0.6]
Степень доверия v: 0.5
Количественная оценка e:
[[-50. -21. -23.]
 [-33. -11.  15.]
 [  0.   5.  10.]]


*Исходный код решения:*

In [59]:
multE = e * q

# суммируем строки
sumE = multE.sum(axis = 1)

# минимальные элементы каждой строки
minE = np.amin(e, axis = 1)

sumEV = sumE * v

minEV = minE * (1 - v)

sumRes = sumEV + minEV

maxE = max(sumRes)

# нахождение индекса максимального значения
result = sumRes.argmax() + 1

*Результат выполнения:*

In [61]:
print(f'Получившаяся сумма строк: {sumE}')
print(f'Минимальные элементы каждой строки: {minE}')
print(f'Получившаяся сумма строк умноженная на степень доверия: {sumEV}')
print(f'Минимальные элементы каждой строки умноженная на степень доверия: {minEV}')
print(f'Сумма двух предыдущих строк: {sumRes}')
print(f'Максимальное значение: {maxE}')
print(f'Выбран вариант №{result}')

Получившаяся сумма строк: [-28.    0.2   7. ]
Минимальные элементы каждой строки: [-50. -33.   0.]
Получившаяся сумма строк умноженная на степень доверия: [-14.    0.1   3.5]
Минимальные элементы каждой строки умноженная на степень доверия: [-25.  -16.5   0. ]
Сумма двух предыдущих строк: [-39.  -16.4   3.5]
Максимальное значение: 3.5
Выбран вариант №3
